# **Stock Return Risk Analyzer**

In [1]:
import numpy as np
from numpy.typing import NDArray
import yfinance

In [2]:
tickers = ["MSFT", "GOOG", "AMZN"]
data = yfinance.download(
    tickers=tickers, start="2025-01-01", end="2026-01-01", group_by="ticker"
)
essential_data  = (data.xs("Close", level=1, axis=1))

[*********************100%***********************]  3 of 3 completed


In [3]:
amazon = essential_data["AMZN"].to_numpy()
google = essential_data["GOOG"].to_numpy()
microsoft = essential_data["MSFT"].to_numpy()

In [4]:
def retrun_percent(price: NDArray) -> NDArray:
    returns  =( price[1:] - price[:-1] )/ price[:-1]
    return returns

In [5]:
def annual_return(returns : NDArray):
    annual_return_ = np.mean(returns) * 252
    return annual_return_

In [6]:
amazon_returns = retrun_percent(amazon)
google_returns = retrun_percent(google)
microsoft_returns = retrun_percent(microsoft)


annual_returns_amazon = annual_return(amazon_returns)
annual_returns_google = annual_return(google_returns)
annual_returns_microsoft = annual_return(microsoft_returns)
#  amazon 
print("\nAmazon")
print(f"Daily mean return :  {(amazon_returns.mean() * 100) :.6f} %") 
print(f"Annual return :  {(annual_returns_amazon * 100):.3f} %") 



#  googl
print("\nGoogle")
print(f"Daily mean return :  {(google_returns.mean() * 100) :.6f} %") 
print(f"Annual return :  {(annual_returns_google * 100):.3f} %") 


# microsoft
print("\nMicrosoft")
print(f"Daily mean return :  {(microsoft_returns.mean() * 100) :.6f} %") 
print(f"Annual return :  {(annual_returns_microsoft * 100):.3f} %") 




Amazon
Daily mean return :  0.042237 %
Annual return :  10.644 %

Google
Daily mean return :  0.222021 %
Annual return :  55.949 %

Microsoft
Daily mean return :  0.072496 %
Annual return :  18.269 %


In [7]:
def annual_risk(returns : NDArray):
    daily_std = np.std(returns,ddof=1)
    annual_std  =daily_std * np.sqrt(252)
    return annual_std

In [8]:
risk_amazon    = annual_risk(amazon_returns)
risk_google    = annual_risk(google_returns)
risk_microsoft = annual_risk(microsoft_returns)

print("\nAmazon")
print(f"Annual Risk : {risk_amazon * 100:.3f} %")

print("\nGoogle")
print(f"Annual Risk : {risk_google * 100:.3f} %")

print("\nMicrosoft")
print(f"Annual Risk : {risk_microsoft * 100:.3f} %")


Amazon
Annual Risk : 34.489 %

Google
Annual Risk : 31.969 %

Microsoft
Annual Risk : 24.299 %


In [9]:
def sharpe_ratio(annual_return: int  , annual_risk: int):
    risk_free = 0.04
    return (annual_return - risk_free) / annual_risk

In [10]:
sharpe_ratio_amazon = sharpe_ratio(annual_returns_amazon , risk_amazon)
sharpe_ratio_google = sharpe_ratio(annual_returns_google , risk_google)
sharpe_ratio_microsoft = sharpe_ratio(annual_returns_microsoft , risk_microsoft)




print(f"sharpe Ratio Amazom : {sharpe_ratio_amazon}")
print(f"sharpe Ratio Microsoft : {sharpe_ratio_microsoft}")
print(f"sharpe Ratio Google : {sharpe_ratio_google}")

sharpe Ratio Amazom : 0.19263201577355982
sharpe Ratio Microsoft : 0.5872337637865587
sharpe Ratio Google : 1.6249789252955378


In [15]:
def covariance(list_returns : list ) : 
    returns_matrix = np.column_stack(list_returns)
    cov = np.cov(returns_matrix.T) *252
    return cov

In [16]:
covariance_matrix = covariance([google_returns, microsoft_returns , amazon_returns])
print(f"Covariance : \n{covariance_matrix}")

Covariance : 
[[0.1022035  0.03313496 0.05962006]
 [0.03313496 0.05904296 0.04907744]
 [0.05962006 0.04907744 0.11895024]]


In [25]:
def portfolio_risk(weights  : NDArray , cov_matrix: NDArray):
    var = weights @ cov_matrix @ weights
    portfolio_risk_ = np.sqrt(var)
    return portfolio_risk_


In [32]:
n = 3 
weights = np.ones(n) / n

p_risk = portfolio_risk(weights , covariance_matrix)

print(f"portfolio risk = {p_risk *100 :.3f} %")

portfolio risk = 25.030 %
