# 1. Numpy:
NumPy (short for Numerical Python) is a foundational library in Python used for scientific computing and working with numbers.

At its core, NumPy provides a highly optimized, multidimensional array object (called ndarray), along with a massive collection of tools and mathematical functions to operate on these arrays efficiently.

## Why use NumPy instead of regular Python lists?
While regular Python lists are flexible and can hold different data types, they are relatively slow and consume a lot of memory when dealing with large amounts of numerical data. NumPy solves this by offering:

### Speed:
 NumPy is written largely in C. Its arrays are stored in continuous blocks of memory, making mathematical operations up to 50x faster than standard Python lists.

### Memory Efficiency:
 NumPy arrays take up significantly less space because they require all elements to be of the exact same data type (e.g., all integers or all floats).

### Built-in Math Power:
 It includes built-in functions for complex math, linear algebra, statistics, and random number generation, saving you from writing complicated loops from scratch.

# 2. Python's List vs Numpy's Array

In [1]:

# if we perform multiplication with python list it will simply duplicate the list
python_list=[1,2,3,4,5]
print(python_list*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
# if we perform mathematical operation with numpy array it will perform vector operation
import numpy as np 
numpy_array=np.array([1,2,3,4,5])
print(type(numpy_array))
print(numpy_array*2)

<class 'numpy.ndarray'>
[ 2  4  6  8 10]


# 3. Time and Size comparision on Array vs List


In [3]:
import time
import sys
list=range(1,1000000)
array=np.arange(1000000)
# time
Start_time_array=time.perf_counter()
final_array=array+1
End_time_array=time.perf_counter()

Start_time_list=time.perf_counter()
final_list=[x +1 for x in list]
End_time_list=time.perf_counter()

print(f"Time taken by array: {End_time_array-Start_time_array}")
print(f"Time taken by list: {End_time_list-Start_time_list}")
print(f"Numpy Array is {np.round((End_time_list-Start_time_list)/(End_time_array-Start_time_array),4)} x times faster than list ")


# size
list_container_size = sys.getsizeof(final_list)
list_elements_size = sum(sys.getsizeof(element) for element in final_list)
true_list_size = list_container_size + list_elements_size

print(f"\nSize taken by array is: {final_array.nbytes}")
print(f"Size taken by list is: {true_list_size}")

Time taken by array: 0.006872700003441423
Time taken by list: 0.09812669997336343
Numpy Array is 14.2778 x times faster than list 

Size taken by array is: 8000000
Size taken by list is: 36448700


# 4. Creating an Array


| Function | Description |
| :--- | :--- |
| `array` | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default |
| `asarray` | Convert input to ndarray, but do not copy if the input is already an ndarray |
| `arange` | Like the built-in `range` but returns an ndarray instead of a list |
| `ones`, <br> `ones_like` | Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a ones array of the same shape and data type |
| `zeros`, <br> `zeros_like` | Like `ones` and `ones_like` but producing arrays of 0s instead |
| `empty`, <br> `empty_like` | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros` |
| `full`, <br> `full_like` | Produce an array of the given shape and data type with all values set to the indicated "fill value"; `full_like` takes another array and produces a filled array of the same shape and data type |
| `eye`, `identity` | Create a square N x N identity matrix (1s on the diagonal and 0s elsewhere) |


In [4]:
# method 1 : From python list
print("\nmethod 1 : From python list")
array1=np.array([1,2,3,4,5])
print(f"Using list one dimension: {array1}")
array1=np.array([list , list])
print(f"Using list two dimension: \n{array1}")

# method 2 : using np.arange() ----> similar to range()
print("\nmethod 2 : using np.arange() ----> similar to range()")
array2=np.arange(0,20)
print(f"Using arange() : {array2}")

# method 3 : using np.linspace() ----> evenly spaced numbers
print("\nmethod 3 : using np.linspace() ----> evenly spaced numbers")
array3=np.linspace(0,20,7)
print(f"Using linspace : {array3}")

# method 4 : creating arrays of zeros
print("\nmethod 4 : creating arrays of zeros")
zero_array=np.zeros((1,2))
print(f"Zeros: {zero_array}")

# method 5 : creating arrays of ones
print("\nmethod 5 : creating arrays of ones")
ones_array=np.ones(5)
print(f"Zeros: {ones_array}")

# method 6 : creating arrays with specific values
print("\nmethod 6 : creating arrays with specific values")
array4=np.full(10,10)
print(array4)

# method 7 : creating Identity matrix
print("\nmethod 7 : creating Identity matrix")
identity_matrix=np.eye(5)
print(f"Identity Matrix : \n{identity_matrix}")


# method 8 : creating empty matrix (contains nonzero garbage values)
print("\nmethod 8 : creating Empty matrix")
empty_matrix=np.empty((5,2))
print(f"Empty Matrix : \n{empty_matrix}")


method 1 : From python list
Using list one dimension: [1 2 3 4 5]
Using list two dimension: 
[[     1      2      3 ... 999997 999998 999999]
 [     1      2      3 ... 999997 999998 999999]]

method 2 : using np.arange() ----> similar to range()
Using arange() : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

method 3 : using np.linspace() ----> evenly spaced numbers
Using linspace : [ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]

method 4 : creating arrays of zeros
Zeros: [[0. 0.]]

method 5 : creating arrays of ones
Zeros: [1. 1. 1. 1. 1.]

method 6 : creating arrays with specific values
[10 10 10 10 10 10 10 10 10 10]

method 7 : creating Identity matrix
Identity Matrix : 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

method 8 : creating Empty matrix
Empty Matrix : 
[[nan  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


# 5. Data types of Numpy
### Table 4-2. NumPy Data Types

| **Type**                          | **Type Code** | **Description**                                                                                |
| --------------------------------- | ------------- | ---------------------------------------------------------------------------------------------- |
| int8, uint8                       | i1, u1        | Signed and unsigned 8-bit (1 byte) integer types                                               |
| int16, uint16                     | i2, u2        | Signed and unsigned 16-bit integer types                                                       |
| int32, uint32                     | i4, u4        | Signed and unsigned 32-bit integer types                                                       |
| int64, uint64                     | i8, u8        | Signed and unsigned 64-bit integer types                                                       |
| float16                           | f2            | Half-precision floating point                                                                  |
| float32                           | f4 or f       | Standard single-precision floating point; compatible with C `float`                            |
| float64                           | f8 or d       | Standard double-precision floating point; compatible with C `double` and Python `float` object |
| float128                          | f16 or g      | Extended-precision floating point                                                              |
| complex64, complex128, complex256 | c8, c16, c32  | Complex numbers represented by two 32-, 64-, or 128-bit floats, respectively                   |
| bool                              | ?             | Boolean type storing `True` and `False` values                                                 |
| object                            | O             | Python object type; a value can be any Python object                                           |
| string_  | S             | Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use `'S10'` |
| unicode_ | U             | Fixed-length Unicode type (number of bytes platform specific); same specification semantics as `string_` (e.g., `'U16'`)     |


In [5]:
array_int=np.array([1,2,3,4,5])
array_float=np.array([1.1,2.2,3.3,4.4,5.5])
array_mixed=np.array([1,2,3.4,5,6.6])

print(f"Integer: {array_int.dtype}")
print(f"FLoat: {array_float.dtype}")
print(f"Mixed: {array_mixed.dtype}") #-----> converted to float

# Memory: Int33/float32 : 4 bytes
# # Memory: Int64/float64 : 8 bytes
print("\nCasting Example:")
# we can cast the data type
print(f"array:  {array_int} , datatype : {array_int.dtype}")
array_int32 = array_int.astype("i4")
print(f"casting to int32 : {array_int32.dtype}")
array_float = array_int.astype(np.float64)
print(f"casting to float : {array_float.dtype}")


example_array = np.array([1.23,42.4,3.3,24.12 , 7.8 ,1.0])
print("casting an array from float to int results in turncating the decimal points")
print(f"array : {example_array} , dtype : {example_array.dtype}")
example_array = example_array.astype(np.int64)
print(f"array : {example_array} , dtype : {example_array.dtype}")


# we can also convert a datatype into int or float from strings if the strings are valid numbers
string_array = np.array(["1.2" ,"3.4", "4.5"])
print(f"array : {string_array} , dtype : {string_array.dtype}")
string_to_float = string_array.astype(np.float64)
print(f"array : {string_to_float} , dtype : {string_to_float.dtype}")


# you can also use another array dtype as an attribute 
print(f"orignal array : {string_to_float} , orignal dtype : {string_to_float.dtype}")
print(f"taking the data type of example array")
another_array = string_to_float.astype(example_array.dtype)
print(f"new array : {another_array} , new dtype : {another_array.dtype}")



Integer: int64
FLoat: float64
Mixed: float64

Casting Example:
array:  [1 2 3 4 5] , datatype : int64
casting to int32 : int32
casting to float : float64
casting an array from float to int results in turncating the decimal points
array : [ 1.23 42.4   3.3  24.12  7.8   1.  ] , dtype : float64
array : [ 1 42  3 24  7  1] , dtype : int64
array : ['1.2' '3.4' '4.5'] , dtype : <U3
array : [1.2 3.4 4.5] , dtype : float64
orignal array : [1.2 3.4 4.5] , orignal dtype : float64
taking the data type of example array
new array : [1 3 4] , new dtype : int64


# 6. Arrays in Numpy 

We can check the dimention of a numpy array by using  .ndim attribute.

We can also check the shape of an array by using shape attribute ---->


1. Zero dimentional (Scalar)

In [6]:
zero_dimentional_array=np.array("A")
print(f"This array is {zero_dimentional_array.ndim} dimentional.")
print(f"Shape is: {zero_dimentional_array.shape}")

This array is 0 dimentional.
Shape is: ()


2. One dimensional (column,)
    
    Also called **Vector**

In [7]:
one_dimentional_array=np.array(["A","B","C"])
print(f"This array is {one_dimentional_array.ndim} dimentional.")
print(f"Shape: {one_dimentional_array.shape}")

This array is 1 dimentional.
Shape: (3,)


3. Two dimensional (rows,column)

    Also called **Matrix**

In [8]:
two_dimentional_array=np.array([["A","B","C"],
                                ["D","E","F"],
                                ["G","H","I"]])
print(f"This array is {two_dimentional_array.ndim} dimentional.")
print(f"Shape: {two_dimentional_array.shape}")

This array is 2 dimentional.
Shape: (3, 3)


4. Multi-dimensional (depth,rows,column)

    Also called **Tensor**

In [9]:
multi_dimentional_array=np.array([[["A","B","C"],["D","E","F"],["G","H","I"]],
                                  [["J","K","L"],["M","N","O"],["P","Q","R"]],
                                  [["S","T","U"],["V","W","X"],["Y","Z"," "]]])
print(f"This array is {multi_dimentional_array.ndim} dimentional.")
print(f"Shape: {multi_dimentional_array.shape}")

This array is 3 dimentional.
Shape: (3, 3, 3)


### 1. Accessing an element in an Array 

We can access an elment in an arraay by two ways
##### 1. Chain indexing like we used to do in list (but it is slower)

In [10]:
print(multi_dimentional_array[1][1][1]+multi_dimentional_array[1][1][2]+multi_dimentional_array[2][0][1])

NOT


##### 2. multidemensional indexing (faster than chain indexing)

In [11]:
print(multi_dimentional_array[1,1,1]+multi_dimentional_array[1,1,2]+multi_dimentional_array[2,0,1])

NOT


# 7. Slicing in Array

array[start:end:step]

ending index is excluded

[] ---> indexing operator

: ---> slicing operator

In [12]:
array=np.array([[["A","B","C"],["D","E","F"],["G","H","I"]],
                [["J","K","L"],["M","N","O"],["P","Q","R"]],
                [["S","T","U"],["V","W","X"],["Y","Z","0"]],
                [["1","2","3"],["4","5","6"],["7","8","9"]]])

##### 1. Slicing one dimension



In [13]:
print(f"array1 shape :\n{array.shape}")
print(f"array 1 :\n{array[0:]}")
print(f"arrry 2 : \n{array[::2]}") # -> [start : stop : step]

array1 shape :
(4, 3, 3)
array 1 :
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '0']]

 [['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]]
arrry 2 : 
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '0']]]


Reversing an Array

In [14]:
print(array[::-1,])

[[['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '0']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]]


##### 2. Slicing two dimensions

In [15]:
print(f"array : \n{array}")



print(f"\ntaking from first two  blocks (depth) and then their first two rows : \n{array[:2,:2]}")
print(f"\ntaking from first two  blocks (depth) then their second third rows : \n{array[:2,1:3]}")
print(array[:2,1:3])
print(array[:2,1:3])
print(array[2:,:2])
print(array[2:,1:])

array : 
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '0']]

 [['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]]

taking from first two  blocks (depth) and then their first two rows : 
[[['A' 'B' 'C']
  ['D' 'E' 'F']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']]]

taking from first two  blocks (depth) then their second third rows : 
[[['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['M' 'N' 'O']
  ['P' 'Q' 'R']]]
[[['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['M' 'N' 'O']
  ['P' 'Q' 'R']]]
[[['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['M' 'N' 'O']
  ['P' 'Q' 'R']]]
[[['S' 'T' 'U']
  ['V' 'W' 'X']]

 [['1' '2' '3']
  ['4' '5' '6']]]
[[['V' 'W' 'X']
  ['Y' 'Z' '0']]

 [['4' '5' '6']
  ['7' '8' '9']]]


##### 3. Slicing three dimensions

In [16]:
print(f"taking first two columns from first row of every block : \n{array[ :,0,:2]}")
print("\n",array[ :,1,:2])
print("\n",array[ :,2,1:])


taking first two columns from first row of every block : 
[['A' 'B']
 ['J' 'K']
 ['S' 'T']
 ['1' '2']]

 [['D' 'E']
 ['M' 'N']
 ['V' 'W']
 ['4' '5']]

 [['H' 'I']
 ['Q' 'R']
 ['Z' '0']
 ['8' '9']]


# 8. Scalar Arithemetic Operations

In [17]:
print("Element wise arithmetic operation between equal size array also called Vectorization")
array1=np.array([1,2,3,4,5,6])
print(array1 + 1)
print(array1 - 2)
print(array1 * 3)
print(array1 / 4)
print(array1 ** 5)


Element wise arithmetic operation between equal size array also called Vectorization
[2 3 4 5 6 7]
[-1  0  1  2  3  4]
[ 3  6  9 12 15 18]
[0.25 0.5  0.75 1.   1.25 1.5 ]
[   1   32  243 1024 3125 7776]


# 9. Vectorized Math functions

##### 1. Basic Arithemetic Operations

In [18]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

# addition
print(f"\nAddition : {np.add(array1,array2)}")

# subtraction
print(f"\nSubtraction : {np.subtract(array1,array2)}")

# multiplication
print(f"\nmultiplication : {np.multiply(array1,array2)}")

# division
print("\nDivision")
print(np.divide(array1,array2))

# floor division -----> //
print("\nFloor Division")
print(np.floor_divide(array2,array1))    

# power
print("\nExponent")
print(np.power(array2,2))    
print(np.power(array1,array2))  

print("\nRemainder")
# compute the remainder of division  
print(np.mod(array2,2))  

# divmod -----> return two arrays : floor_ division and modulus
print("\nFloor division and Remainder")
print(np.divmod(array2,2))  


# return negative of each value (multiply with -1)
print("\nReturn negative of each value")
print(np.negative(array1))

# remove any negative sign
print("\nRemove the negative sign")
print(np.absolute(array1))

matrix=np.array([[1,2],
                 [4,5],
                 [7,8],
                 [10,11]])
print("\nsplit the two arrays vertically")
left,right=np.vsplit(matrix,2)
print(left)
print(right)


print(f"\nDot product: \n{np.dot(left,right)}")
matrix2=np.array([[1,2],
                  [3,4]])
print(f"\ndeterminent : {np.linalg.det(matrix2)}")
print(f"\ninverse : \n{np.linalg.inv(matrix2)}")



Addition : [ 7  9 11 13 15]

Subtraction : [-5 -5 -5 -5 -5]

multiplication : [ 6 14 24 36 50]

Division
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]

Floor Division
[6 3 2 2 2]

Exponent
[ 36  49  64  81 100]
[      1     128    6561  262144 9765625]

Remainder
[0 1 0 1 0]

Floor division and Remainder
(array([3, 3, 4, 4, 5]), array([0, 1, 0, 1, 0]))

Return negative of each value
[-1 -2 -3 -4 -5]

Remove the negative sign
[1 2 3 4 5]

split the two arrays vertically
[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]

Dot product: 
[[27 30]
 [78 87]]

determinent : -2.0000000000000004

inverse : 
[[-2.   1. ]
 [ 1.5 -0.5]]


##### 2. Exponenents and Logarithmics Functions 

In [19]:
# Calculates the exponential (e^x) of all elements.
print(np.exp(array1))


[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [20]:
# Calculates 2^x for all elements.
print(np.exp2(array1))


[ 2.  4.  8. 16. 32.]


In [21]:

# Calculate Natural logarithm (base e) element-wise.
print("logarithms of base e:",np.log(array1))


logarithms of base e: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [22]:

# Calculate Natural logarithm (base 10) element-wise.
print("logarithms of base 10:", np.log10(array1))


logarithms of base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [23]:

# Calculate Natural logarithm (base 2) element-wise.
print("logarithms of base 2:",np.log2(array1))


logarithms of base 2: [0.         1.         1.5849625  2.         2.32192809]


In [24]:

# Computes (e^x - 1) (highly accurate for very small values of x).
print("(e^x - 1): ",np.expm1(array1))


(e^x - 1):  [  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


In [25]:

# Computes log(1 + x)  log of base e (highly accurate for very small values of x)
print("log(1 + x): ",np.log1p(array1))

log(1 + x):  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


##### 3. Trignometric Functions

In [26]:
array1=np.array([2*np.pi,np.pi,np.pi/2])
array2=np.array([-0.7,-0.8,1.00])
print(array1)


[6.28318531 3.14159265 1.57079633]


In [27]:
# Computes sine, cosine, and tangent element-wise.
print(f"Sine values: {np.sin(array1)}")
print(f"Cosine values: {np.cos(array1)}")
print(f"Tangent values: {np.tan(array1)}")


Sine values: [-2.4492936e-16  1.2246468e-16  1.0000000e+00]
Cosine values: [ 1.000000e+00 -1.000000e+00  6.123234e-17]
Tangent values: [-2.44929360e-16 -1.22464680e-16  1.63312394e+16]


In [28]:

# Computes the inverse sine, cosine, and tangent.
print(f"Sine^-1 values: {np.arcsin(array2)}")
print(f"Cosine^-1 values: {np.arccos(array2)}")
print(f"Tangent^-1 values: {np.arctan(array2)}")


Sine^-1 values: [-0.7753975  -0.92729522  1.57079633]
Cosine^-1 values: [2.34619382 2.49809154 0.        ]
Tangent^-1 values: [-0.61072596 -0.67474094  0.78539816]


In [29]:

# Converts radians to degrees element-wise.
print(f"Radian to degrees: {np.degrees(array1)}")
print(f"Radian to degrees: {np.rad2deg(array1)}")


Radian to degrees: [360. 180.  90.]
Radian to degrees: [360. 180.  90.]


In [30]:

# Converts degrees to radians element-wise.
degrees_array=np.array([0,30,45,60,90])
print(f"Degrees to radians: {np.radians(degrees_array)}")
print(f"Degrees to radians: {np.deg2rad(degrees_array)}")


Degrees to radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Degrees to radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


##### 4. Rounding Functions

In [31]:
# Rounds to the given number of decimals.
print(np.round(np.pi,4))
print(np.round(np.e,4))

# Rounds down to the nearest integer.
print(np.floor(np.pi))
# Rounds up to the nearest integer.
print(np.ceil(np.pi))

# removes the decimal part, leaving only the integer part.
print(np.trunc(np.e))

3.1416
2.7183
3.0
4.0
2.0


##### 5. Comparision Functions (Boolean Operation)

In [32]:
marks=np.array([55,63,90,100,85,43,60])

# np.equal(a, b)  ==  Returns True if elements are equal.
# np.not_equal(a, b)  !=   Returns True if elements are not equal.
print(np.equal(marks,100))
print(np.not_equal(marks,100))

# np.greater(a, b)  >  Returns True if a > b.
# np.greater_equal(a, b)  >=  Returns True if a >= b.
print(np.greater(marks,60))
print(np.greater_equal(marks,60))

# np.less(a, b)  <  Returns True if a < b.
# np.less_equal(a, b)  <=  Returns True if a <= b.
print(np.less(marks,60))
print(np.less_equal(marks,60))


[False False False  True False False False]
[ True  True  True False  True  True  True]
[False  True  True  True  True False False]
[False  True  True  True  True False  True]
[ True False False False False  True False]
[ True False False False False  True  True]


## Unary Universal Functions (UFuncs)

Unary universal functions operate on **one input array** and perform an element-wise operation, producing one output array.
## Table 4-4. Some Unary Universal Functions

| Function | Description |
|----------|-------------|
| `abs`, `fabs` | Compute the absolute value element-wise for integer, floating-point, or complex values. |
| `sqrt` | Compute the square root of each element (equivalent to `arr ** 0.5`). |
| `square` | Compute the square of each element (equivalent to `arr ** 2`). |
| `exp` | Compute the exponent `e^x` of each element. |
| `log`, `log10`, `log2`, `log1p` | Natural logarithm (base *e*), base-10 logarithm, base-2 logarithm, and `log(1 + x)`, respectively. |
| `sign` | Compute the sign of each element: `1` (positive), `0` (zero), or `-1` (negative). |
| `ceil` | Compute the ceiling of each element (smallest integer greater than or equal to the value). |
| `floor` | Compute the floor of each element (largest integer less than or equal to the value). |
| `rint` | Round elements to the nearest integer, preserving the data type. |
| `modf` | Return the fractional and integral parts of the array as separate arrays. |
| `isnan` | Return a Boolean array indicating whether each value is NaN (Not a Number). |
| `isfinite`, `isinf` | Return Boolean arrays indicating whether each element is finite (not `±inf`, not `NaN`) or infinite, respectively. |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions. |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric and inverse hyperbolic trigonometric functions. |
| `logical_not` | Compute the element-wise logical NOT of each value (equivalent to `~arr` for Boolean arrays). |

## Binary Universal Functions (UFuncs)

Binary universal functions operate on **two input arrays** (or an array and a scalar) and perform element-wise operations between corresponding elements.
## Table 4-5. Some Binary Universal Functions

| Function | Description |
|----------|-------------|
| `add` | Add corresponding elements in arrays. |
| `subtract` | Subtract elements in the second array from the first array. |
| `multiply` | Multiply corresponding array elements. |
| `divide`, `floor_divide` | Perform division or floor division (truncating the remainder). |
| `power` | Raise elements in the first array to the powers specified by the second array. |
| `maximum`, `fmax` | Compute the element-wise maximum (`fmax` ignores `NaN`). |
| `minimum`, `fmin` | Compute the element-wise minimum (`fmin` ignores `NaN`). |
| `mod` | Compute the element-wise modulus (remainder after division). |
| `copysign` | Copy the sign of values in the second argument to the values in the first argument. |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparisons, returning a Boolean array (equivalent to `>`, `>=`, `<`, `<=`, `==`, `!=`). |
| `logical_and` | Compute the element-wise logical AND (`&`) operation. |
| `logical_or` | Compute the element-wise logical OR (`\|`) operation. |
| `logical_xor` | Compute the element-wise logical XOR (`^`) operation. |

# 10. Array Manipulation

Changing the shape of Array is Common in Data Proccessing

In [33]:
array=np.arange(12)
print(f"array: {array}")

# Reshape , changes the view , not the data
# Must match the total no of elements (3x4=12)
reshaped_array=array.reshape((3,4))
print(f"\nReshaped : \n{reshaped_array}")

# Flattened ----> convert an array in 1 D
# ravel -----> just give you the view of the data   
flattened_array=reshaped_array.flatten()
print(f"\nFlattened Array: \n{flattened_array}")

#  Reshape with -1 auto calculate the dimension
auto_reshaped=flattened_array.reshape(4,-1)
print(f"\nAuto Reshaped : \n{auto_reshaped}")

#  Transpose -----> flip the axis of array
print(f"\nOrignal Array:\n {auto_reshaped}")
print(f"\nTransposed Array:\n {auto_reshaped.T}")

rng=np.random.default_rng()
grid=rng.integers(low=1,high=17,size=(4,4))
#  split() -----> split the array into equal parts
print(f"\nSplited array : \n{np.split(flattened_array,4)}")
#  hsplit() ----> split the array horzontally
print(f"\n Orignal Array :\n {grid}")
print(f"\n horizontally split Array :\n {np.hsplit(grid,2)}")
print(f"\n vertical split Array :\n {np.vsplit(grid,2)}")



# Concatenation
arr1=np.array([[1,2,3,4],
               [5,6,7,8]])
arr2=np.array([[9,10,11,12],
                 [13,14,15,16]])

print(f"\nArray 1 : \n {arr1}")
print(f"\nArray 2 : \n {arr2}")
print("\nVertical concatenation (vstack)")
print(f" \nVStack:\n {np.vstack((arr1,arr2))}")
print("\nHorizontal concatenation (hstack)")
print(f" \nHStack:\n {np.hstack((arr1,arr2))}")
print("\nUsing Concatenation")
print(f"\nby concatenation using axix 0 :\n {np.concatenate((arr1,arr2),axis=0)}") # axis: 0 ----> vertical stack
print(f"\nby concatenation using axix 1:\n {np.concatenate((arr1,arr2),axis=1)}") # axis: 1 ----> horizontal stack

array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Auto Reshaped : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Orignal Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Transposed Array:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]



Splited array : 
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

 Orignal Array :
 [[10  7 12 14]
 [16  7 12  2]
 [ 8 16  1  2]
 [ 3  1  8 14]]

 horizontally split Array :
 [array([[10,  7],
       [16,  7],
       [ 8, 16],
       [ 3,  1]]), array([[12, 14],
       [12,  2],
       [ 1,  2],
       [ 8, 14]])]

 vertical split Array :
 [array([[10,  7, 12, 14],
       [16,  7, 12,  2]]), array([[ 8, 16,  1,  2],
       [ 3,  1,  8, 14]])]

Array 1 : 
 [[1 2 3 4]
 [5 6 7 8]]

Array 2 : 
 [[ 9 10 11 12]
 [13 14 15 16]]

Vertical concatenation (vstack)
 
VStack:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Horizontal concatenation (hstack)
 
HStack:
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]

Using Concatenation

by concatenation using axix 0 :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

by concatenation using axix 1:
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


# 11. Dimensions and Axes

**Key Concepts:**
- **Dimension (ndim)**: Number of axes (1D=1, 2D=2, 3D=3)
- **Axis**: The dimension along which an operation is performed (starts at 0)
- **Shape**: Size of each dimension (e.g., (3, 4) = 3 rows, 4 columns)
- **For 2D arrays**: `axis=0` = rows (vertical), `axis=1` = columns (horizontal)

In [34]:
arr_1D=np.arange(1,9)
arr_2D=np.array([np.arange(1,9),np.arange(9,17)])
print(f" 1D Array: \n{arr_1D}")
print(f" 1D array Shape: {arr_1D.shape} dimension: {arr_1D.ndim}")
print(f" 2D Array: \n{arr_2D}")
print(f" 2D array Shape: {arr_2D.shape} dimension: {arr_2D.ndim}")

 1D Array: 
[1 2 3 4 5 6 7 8]
 1D array Shape: (8,) dimension: 1
 2D Array: 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
 2D array Shape: (2, 8) dimension: 2


In [35]:
# 2D operations
# axis=0: collapse rows (operate down columns) → one value per column
sum0axis=np.sum(arr_2D,axis=0)
print(f"Sum0Axis:\n{sum0axis} \n shape:{sum0axis.shape}, dimension :{sum0axis.ndim}")

# axis=1: collapse columns (operate across rows) → one value per row
sum1axis=np.sum(arr_2D,axis=1)
print(f"Sum1Axis:\n{sum1axis} \n shape:{sum1axis.shape}, dimension :{sum1axis.ndim}")


Sum0Axis:
[10 12 14 16 18 20 22 24] 
 shape:(8,), dimension :1
Sum1Axis:
[ 36 100] 
 shape:(2,), dimension :1


In [36]:
# 3D operation
arr_3D1=np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print(f"3D Array: \n{arr_3D1} \n shape:{arr_3D1.shape} , dimension:{arr_3D1.ndim}\n")

# sum 0 axis
sumaxis0=np.sum(arr_3D1,axis=0)
print(f" Sum 0 Axis (across depth):\n{sumaxis0} \n Shape:{sumaxis0.shape}, Dimension:{sumaxis0.ndim}\n")


# sum 1 axis
sumaxis1=np.sum(arr_3D1,axis=1)
print(f" Sum 1 Axis (across row):\n{sumaxis1} \n Shape:{sumaxis1.shape}, Dimension:{sumaxis1.ndim}\n")


# sum 2 axis
sumaxis2=np.sum(arr_3D1,axis=2)
print(f" Sum 2 Axis (across column):\n{sumaxis2} \n Shape:{sumaxis2.shape}, Dimension:{sumaxis2.ndim}")

3D Array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 shape:(2, 2, 3) , dimension:3

 Sum 0 Axis (across depth):
[[ 8 10 12]
 [14 16 18]] 
 Shape:(2, 3), Dimension:2

 Sum 1 Axis (across row):
[[ 5  7  9]
 [17 19 21]] 
 Shape:(2, 3), Dimension:2

 Sum 2 Axis (across column):
[[ 6 15]
 [24 33]] 
 Shape:(2, 2), Dimension:2


In [37]:
print("Transposing array:")
arr_2D=np.array([np.arange(1,9),np.arange(9,17)])
print(f"array : \n{arr_2D}")

print(f"transposing array : \n{arr_2D.T}")

print("we can also do the same with np.swapaxes")
print(f"by swapping axis : \n{arr_2D.swapaxes(1,0)}")

Transposing array:
array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
transposing array : 
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]
we can also do the same with np.swapaxes
by swapping axis : 
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]


# 12. Broadcasting 

NumPy broadcasting is one of the most powerful concepts in Python data science. It is a set of rules that allows NumPy to perform element-wise operations (like addition, subtraction, multiplication) on arrays of different shapes.

Instead of requiring you to manually duplicate data to make the arrays match in size, NumPy automatically "broadcasts" the smaller array across the larger one. This happens under the hood at the C-level, making it highly memory-efficient and incredibly fast

##### 1. Rules of Broadcasting:

When you perform an operation on two arrays, NumPy compares their shapes element by element, starting from the rightmost (trailing) dimension and working its way to the left.

Two dimensions are considered compatible if:

They are exactly equal.

One of them is 1.

If these conditions are not met, NumPy throws a ValueError: operands could not be broadcast together."""


##### 2. How to check in which array weather a row is going to expand or a column?


1. determine the shape of both array
2. write shape of array A on top of Array B pushing them all the way to the right.
3. If one array has fewer dimensions (fewer numbers in its shape) than the other, write a 1 in the empty spaces on the left.
4. If the 1 is in the Rows spot (left), the array expands vertically (copies the row downwards).
5. If the 1 is in the Columns spot (right), the array expands horizontally (copies the column across).


In [38]:
array1=np.array([1,2,3,4,5])
                
array2=np.array([[1],[2],[3],[4],[5]])
print(array1.shape)
print(array2.shape)
print(np.broadcast_arrays(array1,array2))
print(array1*array2)



(5,)
(5, 1)
(array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]]), array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]]))
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [39]:

# making a list from for loop and converting it into an array and broadcast it.
lisst=[]
lisst2=[]
my_list=[lisst.append(i) for i in range(1,50)]
my_list2=[lisst2.append([i]) for i in range(1,50)]
my_array1=np.array(lisst)
my_array2=np.array(lisst2)
print(my_array1.shape)
print(my_array2.shape)

print(my_array1*my_array2)


(49,)
(49, 1)
[[   1    2    3 ...   47   48   49]
 [   2    4    6 ...   94   96   98]
 [   3    6    9 ...  141  144  147]
 ...
 [  47   94  141 ... 2209 2256 2303]
 [  48   96  144 ... 2256 2304 2352]
 [  49   98  147 ... 2303 2352 2401]]


np.newaxis is the absolute most important tool for ML broadcasting. It temporarily adds a dimension of size 1 to an array, forcing NumPy to broadcast exactly how you want it to.


In [40]:
arr=np.array([1,2,3,4]) #( , 4)
arr2=np.array([1,2,3,4]) #( , 4)
arr3=arr[:,np.newaxis] # add dimension of size 1 make it compatible for broadcast
print(arr.shape)
print(arr2.shape)
print(arr3.shape)
print(np.broadcast_arrays(arr2,arr3))

(4,)
(4,)
(4, 1)
(array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]]))


# 13. Aggregation

In NumPy, an aggregate function (often called a "reduction" function) is a method that takes a large array of data and computes a summary statistic, effectively "squashing" the data down into a single value or a significantly smaller array.

Instead of looking at millions of individual data points, an aggregate function gives you the big picture—like the total, the average, or the extreme values.


##### 1. Where and When Do We Use Them?


You use aggregate functions practically every time you perform data analysis, scientific computing, or machine learning preparation. Specific use cases include:

Data Summarization: Finding the total revenue from an array of sales figures or the average age in a dataset of users.

Statistical Analysis: Calculating variance and standard deviation to understand how spread out your data is.

Finding Extremes: Locating the absolute highest or lowest values (and their exact index positions) to identify peaks, troughs, or anomalies.

Handling Missing Data: Using "safe" versions of these functions (like nansum instead of sum) to calculate statistics while ignoring missing values (NaN).

Conditional Checks: Quickly checking if all data points pass a certain threshold, or if any anomalies exist in a massive dataset.

In [41]:
# nan ----> not a number
array=np.array([[1,2,3,4,5,],
                [6,7,8,9,10]])


nan_array=np.array([[1,2,3,np.nan,5],
                    [6,7,8,9,10]])
# print(np.nan)

# do sum of all elements
print(np.sum(array))


55


In [42]:

# do the sum column wise
print(np.sum(array,axis=0))
# do the sum row wise wise
print(np.sum(array,axis=1))


[ 7  9 11 13 15]
[15 40]


In [43]:
# using nansum to ignore missing data
print(np.nansum(nan_array)) #-----> 55
print(np.sum(nan_array))  # ------> nan (not a number)


51.0
nan


In [44]:


# gives the product of all elements
print(np.prod(nan_array))
print(np.nanprod(nan_array))


nan
907200.0


In [45]:


# find the maximum and minimum value in the whole array
print(f" Min : {np.min(array)}")
print(f" Max : {np.max(array)}")


 Min : 1
 Max : 10


In [46]:


# find the maximum and minimum value's index in the whole array

print(f" Min : {np.argmin(array)}")
print(f" Max : {np.argmax(array)}")


 Min : 0
 Max : 9


In [47]:


# find the maximum and minimum value column wise in the whole array
print(f" Min : {np.min(array,axis=0)}")
print(f" Max : {np.min(array,axis=0)}")


 Min : [1 2 3 4 5]
 Max : [1 2 3 4 5]


In [48]:

# find the maximum and minimum value  row wise in the whole array
print(f" Min : {np.min(array,axis=1)}")
print(f" Max : {np.max(array,axis=1)}")



 Min : [1 6]
 Max : [ 5 10]


In [49]:

# calculates the range of the data
print(f"Range: {np.ptp(array)}")


Range: 9


In [50]:

# calculates the mean 
print(f"Mean: {np.mean(array)}")


Mean: 5.5


In [51]:

# calculates the median
print(f"Median: {np.median(array)}")


Median: 5.5


In [52]:

# calculates the standard deviation
print(f"SD: {np.std(array)}")

# calculate the variance (square of SD)
print(f"Var: {np.var(array)}")

# determine the percentile
print(np.percentile(array,70))


SD: 2.8722813232690143
Var: 8.25
7.3


In [53]:
# returns true if any of the value meet the condition
print(f"Is any element in the array is greater than 5: {np.any(array>5)}")
print(f"Is any element in the array is greater than 10: {np.any(array>10)}")

# return true only if all elements of an array meets the condition
print(f" Is all elements is greater than 0: {np.all(array>0)}")
print(f" Is all elements is greater than 5: {np.all(array>5)}")
print(f" Is all elements is less than 11: {np.all(array<11)}")


Is any element in the array is greater than 5: True
Is any element in the array is greater than 10: False
 Is all elements is greater than 0: True
 Is all elements is greater than 5: False
 Is all elements is less than 11: True


In [54]:
# returns true if any of the value meet the condition
print(f"Is any element in teh array is greater than 5: {np.any(array>5)}")
print(f"Is any element in teh array is greater than 10: {np.any(array>10)}")

# return true only if all elements of an array meets the condition
print(f" Is all elements is greater than 0: {np.all(array>0)}")
print(f" Is all elements is greater than 5: {np.all(array>5)}")
print(f" Is all elements is less than 11: {np.all(array<11)}")


Is any element in teh array is greater than 5: True
Is any element in teh array is greater than 10: False
 Is all elements is greater than 0: True
 Is all elements is greater than 5: False
 Is all elements is less than 11: True


# 14. Filtering In Numpy

In standard Python, if you want to filter a list, you typically have to write a for loop, check every single item with an if statement, and append the passing items to a new list. This is computationally expensive and slow for massive datasets.

NumPy solves this elegantly using a concept known formally as Boolean Indexing (often referred to as Masking).

In NumPy, filtering does not happen by deleting elements. Instead, it is a two-step process:

The Condition: You apply a logical condition to your array. Because NumPy operations are vectorized (applied to the whole array at once in C-code), this condition evaluates every single element simultaneously.

The Mask: The result of this condition is a new array of the exact same shape, filled entirely with True and False values. This is your "Boolean Mask."

The Application: You pass this Mask back into the original array using square brackets []. NumPy acts like a sieve, letting only the elements that align with a True value pass through into the final output array.

In [55]:
Ages=np.array([[12,23,45,31,19,17,16],
               [20,11,18,26,65,99,24]])
teenager=Ages[Ages <20]
print(teenager)

[12 19 17 16 11 18]


In [56]:
# we can also store the expresion in a variable , it is called Masking
mask=Ages  >=18 
adults=Ages[mask]
print(adults)

[23 45 31 19 20 18 26 65 99 24]


In [57]:
even_ages=Ages[Ages % 2 == 0]
odd_ages=Ages[Ages % 2 == 1]
print(odd_ages)
print(even_ages)

[23 45 31 19 17 11 65 99]
[12 16 20 18 26 24]


In [58]:
extreme_ages=Ages[(Ages<16)|(Ages>=65)]
print(extreme_ages)

[12 11 65 99]


In [59]:
#.where() replace the values that don't meet the condition with the given value (usually 0 or -1)
adults=np.where(Ages >=18 , Ages ,0)
print(adults)

numbers=np.arange(12)
print(np.where(numbers>5,numbers*10,numbers))

[[ 0 23 45 31 19  0  0]
 [20  0 18 26 65 99 24]]
[  0   1   2   3   4   5  60  70  80  90 100 110]


# 15. Random Numbers in Numpy

1. The standard random module: Good for basic Python lists and simple scripts.
2. The numpy.random module: The industry standard for data science, game dev, and AI. It generates entire arrays of random numbers instantly using C-level optimizations.

Computers cannot generate truly random numbers; they are purely logical machines. Instead, they use complex mathematical formulas called Pseudo-Random Number Generators (PRNGs).

| Method | Description |
|--------|-------------|
| `permutation` | Return a random permutation of a sequence, or return a permuted range |
| `shuffle` | Randomly permute a sequence in place |
| `uniform` | Draw samples from a uniform distribution |
| `integers` | Draw random integers from a given low-to-high range |
| `standard_normal` | Draw samples from a normal distribution with mean 0 and standard deviation 1 |
| `binomial` | Draw samples from a binomial distribution |
| `normal` | Draw samples from a normal (Gaussian) distribution |
| `beta` | Draw samples from a beta distribution |
| `chisquare` | Draw samples from a chi-square distribution |
| `gamma` | Draw samples from a gamma distribution |
| `uniform` | Draw samples from a uniform `[0, 1)` distribution |

In [60]:
# we ca also set the sed so the numbers generated are always same. 
rng=np.random.default_rng(seed=1)
print(rng.integers(1,100 ,size = (2,2)))
print(np.random.randint(1,6))

[[47 51]
 [75 95]]
1


In [61]:
print(rng.integers(1,100,size=10))
print(np.random.randint(1,100,size=10))

[ 4 15 82 94 25 31 87 42 28 82]
[86 10 21 20  9 28 76 87 85 52]


In [62]:
print(rng.integers(1,100,size=(4,4)))

[[26 41 64 55]
 [ 9  3 86 75]
 [83 54 81 33]
 [45 79 13 31]]


In [63]:
print(np.random.uniform(-1.0,1.0, size=(2,2)))

[[ 0.59814349  0.91615676]
 [-0.60851477 -0.85764255]]


In [64]:
fruits=np.array(["apple","banana","orange","coconut","pineapple","cherry"])
rng.shuffle(fruits)
print(fruits)

['apple' 'orange' 'cherry' 'banana' 'coconut' 'pineapple']


In [65]:
#  we can also set the probability of element to be selected
print(rng.choice(fruits,size=(3,3),p=[0.7,0.1,0.05,0.05,0.05,0.05]))

[['apple' 'apple' 'orange']
 ['apple' 'apple' 'pineapple']
 ['pineapple' 'orange' 'apple']]


In [66]:
# .permutation did the same thing as shuffle but it gives a brand new array
shuffled_array=np.random.permutation(fruits)
print(shuffled_array)

['apple' 'cherry' 'coconut' 'pineapple' 'banana' 'orange']


# 16 . Boolean Indexing

In [67]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12],
                  [13,14,15]])
names_array = np.array(["bob" , "joe" ,"smith","bob" , "joe" ])
print(names_array == "joe")

print("printing the rows corresponds to the true value of names_array")
print(array[names_array =="joe"])
print("since 1 and 4 index has true values so the 1 and 4 index of array get printed")


print("\newe can also check whether on any of all values are present using |(or) and &(and)")
print(array[(names_array =="joe") | (names_array == "smith")])



print("\n we can also set the values by boolean indexing")
numbers = np.array([1,2,3,4,5,6,7,8,9,0])
numbers[numbers > 5] = 10
print(numbers)



[False  True False False  True]
printing the rows corresponds to the true value of names_array
[[ 4  5  6]
 [13 14 15]]
since 1 and 4 index has true values so the 1 and 4 index of array get printed

ewe can also check whether on any of all values are present using |(or) and &(and)
[[ 4  5  6]
 [ 7  8  9]
 [13 14 15]]

 we can also set the values by boolean indexing
[ 1  2  3  4  5 10 10 10 10  0]


# 17. Array Oriented Programming

In [68]:
points = np.arange(-5 , 5 ,0.01) # 100 equally spaced elements

x , y  = np.meshgrid(points , points) #a NumPy function used to generate a coordinate grid from 1D coordinate vectors

z = np.sqrt(x**2 + y**2)
print(z)

[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


In [69]:
# expresing condition logic as array operation
arr1= np.array([1,2,3,4,5,6,7,8,9])
arr2= np.array([10,20,30,40,50,60,70,80,90])
cond = np.array([True , False , True ,False,False, True ,True , False ,False])


z= [(int(x) if c else int(y)) for x ,y ,c in zip(arr1 ,arr2 ,cond)]
print(f"using list comprehension : {z}")



print("above list comprehension is same as np.where() function")

print(np.where(cond ,arr1 , arr2))

print(f"set number less than 5 to zero : {np.where(arr1<5 , 0 , arr1)}")

using list comprehension : [1, 20, 3, 40, 50, 6, 7, 80, 90]
above list comprehension is same as np.where() function
[ 1 20  3 40 50  6  7 80 90]
set number less than 5 to zero : [0 0 0 0 5 6 7 8 9]


# 18. Some Statistical and Mathematical Functions
# NumPy Statistical Functions


| Function | Basic Parameters | Description |
|----------|------------------|-------------|
| `np.mean()` | `a, axis=None, dtype=None, keepdims=False` | Computes the arithmetic mean (average). |
| `np.median()` | `a, axis=None, overwrite_input=False, keepdims=False` | Computes the median (middle value). |
| `np.average()` | `a, axis=None, weights=None, returned=False` | Computes the weighted average. |
| `np.std()` | `a, axis=None, dtype=None, ddof=0, keepdims=False` | Computes the standard deviation. |
| `np.var()` | `a, axis=None, dtype=None, ddof=0, keepdims=False` | Computes the variance. |
| `np.min()` | `a, axis=None, keepdims=False, initial=None` | Returns the minimum value. |
| `np.max()` | `a, axis=None, keepdims=False, initial=None` | Returns the maximum value. |
| `np.argmin()` | `a, axis=None` | Returns the index of the minimum value. |
| `np.argmax()` | `a, axis=None` | Returns the index of the maximum value. |
| `np.percentile()` | `a, q, axis=None, method='linear'` | Computes the q-th percentile. |
| `np.quantile()` | `a, q, axis=None, method='linear'` | Computes the q-th quantile. |
| `np.nanmean()` | `a, axis=None, dtype=None` | Computes the mean while ignoring `NaN` values. |
| `np.nanmedian()` | `a, axis=None` | Computes the median while ignoring `NaN` values. |
| `np.nanstd()` | `a, axis=None, ddof=0` | Computes the standard deviation ignoring `NaN`s. |
| `np.nanvar()` | `a, axis=None, ddof=0` | Computes the variance ignoring `NaN`s. |
| `np.nanmin()` | `a, axis=None` | Returns the minimum ignoring `NaN`s. |
| `np.nanmax()` | `a, axis=None` | Returns the maximum ignoring `NaN`s. |
| `np.sum()` | `a, axis=None, dtype=None, keepdims=False` | Computes the sum of elements. |
| `np.nansum()` | `a, axis=None, dtype=None` | Computes the sum while ignoring `NaN`s. |
| `np.prod()` | `a, axis=None, dtype=None` | Computes the product of elements. |
| `np.nanprod()` | `a, axis=None, dtype=None` | Computes the product while ignoring `NaN`s. |
| `np.cumsum()` | `a, axis=None, dtype=None` | Computes the cumulative sum. |
| `np.cumprod()` | `a, axis=None, dtype=None` | Computes the cumulative product. |
| `np.diff()` | `a, n=1, axis=-1` | Computes the n-th discrete difference between consecutive elements. |
| `np.ptp()` | `a, axis=None` | Returns the range (`max - min`). |
| `np.corrcoef()` | `x, y=None, rowvar=True` | Computes the correlation coefficient matrix. |
| `np.cov()` | `m, y=None, rowvar=True, bias=False` | Computes the covariance matrix. |
| `np.histogram()` | `a, bins=10, range=None, density=False` | Computes the histogram of data. |
| `np.bincount()` | `x, weights=None, minlength=0` | Counts occurrences of non-negative integers. |
| `np.count_nonzero()` | `a, axis=None` | Counts non-zero elements. |
| `np.unique()` | `ar, return_counts=False, return_index=False` | Returns unique values (optionally with counts). |
| `np.all()` | `a, axis=None` | Returns `True` if all elements are `True`. |
| `np.any()` | `a, axis=None` | Returns `True` if at least one element is `True`. |

---

## Frequently Used Statistical Functions

| Function | Purpose |
|----------|---------|
| `np.mean()` | Average |
| `np.median()` | Median |
| `np.average()` | Weighted Average |
| `np.std()` | Standard Deviation |
| `np.var()` | Variance |
| `np.min()` | Minimum |
| `np.max()` | Maximum |
| `np.percentile()` | Percentiles |
| `np.quantile()` | Quantiles |
| `np.corrcoef()` | Correlation Matrix |
| `np.cov()` | Covariance Matrix |
| `np.histogram()` | Frequency Distribution |
| `np.unique(return_counts=True)` | Frequency Count |
| `np.ptp()` | Data Range | 

# 19 . Sorting 
# NumPy Sorting Functions


| Function | Basic Parameters | Description |
|----------|------------------|-------------|
| `np.sort()` | `a, axis=-1, kind='quicksort'` | Returns a sorted copy of the array. |
| `ndarray.sort()` | `axis=-1, kind='quicksort'` | Sorts the array in-place. |
| `np.argsort()` | `a, axis=-1, kind='quicksort'` | Returns the indices that would sort the array. |
| `np.lexsort()` | `keys, axis=-1` | Performs an indirect stable sort using multiple keys. |
| `np.msort()` | `a` | Sorts along the first axis (deprecated; use `np.sort(axis=0)`). |
| `np.partition()` | `a, kth, axis=-1` | Partially sorts so the k-th element is in its final position. |
| `np.argpartition()` | `a, kth, axis=-1` | Returns indices for a partial sort. |
| `np.searchsorted()` | `a, v, side='left', sorter=None` | Finds insertion indices to maintain sorted order. |
| `np.nonzero()` | `a` | Returns indices of non-zero elements. |
| `np.where()` | `condition, x=None, y=None` | Returns indices satisfying a condition or selects elements. |
| `np.extract()` | `condition, arr` | Extracts elements that satisfy a condition. |
| `np.take_along_axis()` | `arr, indices, axis` | Selects values using indices along an axis. |
| `np.put_along_axis()` | `arr, indices, values, axis` | Places values into an array using indices along an axis. |
| `np.unique()` | `ar, return_index=False, return_inverse=False, return_counts=False` | Returns sorted unique elements and optional information. |

---

# Common Sorting Algorithms (`kind` Parameter)


| Kind | Stable | Average Time | Description |
|------|--------|--------------|-------------|
| `'quicksort'` | ❌ No | **O(n log n)** | Fastest general-purpose sorting algorithm (default). |
| `'mergesort'` | ✅ Yes | **O(n log n)** | Stable sorting algorithm. |
| `'heapsort'` | ❌ No | **O(n log n)** | Heap-based sorting algorithm. |
| `'stable'` | ✅ Yes | **O(n log n)** | Uses the best stable algorithm available (recommended for stable sorting). |

---

# Frequently Used Sorting Functions

| Function | Purpose |
|----------|---------|
| `np.sort()` | Sort an array |
| `ndarray.sort()` | Sort an array in-place |
| `np.argsort()` | Get sorting indices |
| `np.partition()` | Find k-th smallest/largest element efficiently |
| `np.argpartition()` | Indices for partial sorting |
| `np.searchsorted()` | Binary search in a sorted array |
| `np.lexsort()` | Multi-key sorting |
| `np.unique()` | Sorted unique elements |
| `np.where()` | Conditional indexing |
| `np.nonzero()` | Indices of non-zero elements |

In [70]:
arr =  rng.uniform(1.00 , 20.00 , size=20)
print(f"\norignal array :\n {arr}")
print(f"\nsorted array :\n {np.sort(arr)}")



arr2 = rng.uniform(1.0 , 10.00 , size = (5,5))

print(f"\nOrignal Array : \n{arr2}")

print(f"\nsorted along axis 0 (down the column): \n{np.sort(arr2 ,axis=0)}")
print(f"\nsorted along axis 1 (across the row): \n{np.sort(arr2 ,axis=1)}")



orignal array :
 [ 6.26093288  4.05238817 19.42858285 10.80530313  3.20144664 12.84630536
 15.75697917 12.64706272 18.42865639  1.75226466 11.043196    9.72738177
  2.184642   13.18523521 17.20002393 12.26587934  5.94185151 16.9577489
 10.68042175 10.7068888 ]

sorted array :
 [ 1.75226466  2.184642    3.20144664  4.05238817  5.94185151  6.26093288
  9.72738177 10.68042175 10.7068888  10.80530313 11.043196   12.26587934
 12.64706272 12.84630536 13.18523521 15.75697917 16.9577489  17.20002393
 18.42865639 19.42858285]

Orignal Array : 
[[7.77727187 2.33129832 8.37664047 7.14958215 8.08387247]
 [2.72454633 8.22127745 2.72191533 1.73397356 8.69704277]
 [8.75155147 8.88883387 5.24718747 3.4664355  1.06382646]
 [6.81148806 7.47918445 8.52012295 3.53690045 2.9369635 ]
 [6.75398242 8.2454935  9.67303786 2.35472347 5.33991149]]

sorted along axis 0 (down the column): 
[[2.72454633 2.33129832 2.72191533 1.73397356 1.06382646]
 [6.75398242 7.47918445 5.24718747 2.35472347 2.9369635 ]
 [6.811488