# **Activation Functions**
**Definition:**

An **activation function** is a mathematical function applied to the output of a neuron in a neural network. It determines whether and how strongly the neuron's output is passed to the next layer, introducing **non-linearity** so that the network can learn and model complex patterns in data.

**Purpose:**

* Introduces non-linearity into the neural network.
* Helps the network learn complex relationships.
* Determines the output of each neuron.

**Common Activation Functions:**

* Sigmoid
* ReLU (Rectified Linear Unit)
* Softmax

In [8]:
import sys
import os


sys.path.append('./Phase 2/Projects/Core Vectorized Operations')




import numpy as np
from Activation_functions import sigmoid , relu , softmax


## 1. Sigmoid Function

**Definition:**

The **Sigmoid function** is an activation function that maps any real-valued input to a value between **0 and 1**, making it useful for representing probabilities in binary classification problems.

### Formula

$$
\sigma(x)=\frac{1}{1+e^{-x}}
$$

where:

* (x) = input value
* (e) = Euler's number (approximately 2.71828)

### Output Range


$$0 < \sigma(x) < 1$$



In [9]:
x = np.array([-3, -1, 0, 1, 3])
print(f"Sigmoid : \n{sigmoid(x)}")

Sigmoid : 
[0.04742587 0.26894142 0.5        0.73105858 0.95257413]


## 2. ReLU (Rectified Linear Unit)

**Definition:**

The **Rectified Linear Unit (ReLU)** is an activation function that returns the input directly if it is positive; otherwise, it returns zero. It is the most widely used activation function in the hidden layers of deep neural networks.

### Formula


$$\text{ReLU}(x)=\max(0,x)$$


### Output Range


$$0 \leq \text{ReLU}(x) < \infty$$



In [10]:
array = np.array([1,-1,2,-2,3,-3,4,-4,5,-5,6,-6])
print(f"Relative linear unit : \n{relu(array)}")

Relative linear unit : 
[1 0 2 0 3 0 4 0 5 0 6 0]



# 3. Softmax Function

**Definition:**

The **Softmax function** is an activation function that converts a vector of real-valued scores into a probability distribution, where each output lies between **0 and 1**, and the sum of all output probabilities equals **1**. It is commonly used for **multi-class classification** problems.

### Formula


$$\text{Softmax}(x_i)=
\frac{e^{x_i}}
{\sum_{j=1}^{n}e^{x_j}}
$$
where:

* ($x_i$) = score of the ($i^{th}$) class
* (n) = total number of classes

### Output Range


$$0 < P(x_i) < 1$$


and


$$\sum_{i=1}^{n}P(x_i)=1$$





In [ ]:
array = np.array([[2.0, 1.0, 0.1],   
                   [0.5, 1.5, 2.0]])

new_array = softmax(array)

print(f"Softmax : \n{new_array}")
print(f"\nsum along axis 1 : \n{np.sum(new_array ,axis=1)}")
# sum along of elements along axis 1 is equal to zero Proved!

Softmax : 
[[0.65900114 0.24243297 0.09856589]
 [0.12195165 0.33149896 0.54654939]]

sum along axis 1 : 
[1. 1.]


# **Euclidean Distance**



In [16]:
from vector_distance_metrics import l2_distance , cosine_similarity


## 1. Cosine Similarity

## Definition

**Cosine Similarity** measures the similarity between two vectors by calculating the **cosine of the angle** between them. It focuses on the **direction** of the vectors rather than their magnitude (length).

In simple words:

> It tells **how similar two vectors point in the same direction**, regardless of how large they are.

---

## Formula

$$
\boxed{\text{Cosine Similarity}=
\frac{\mathbf{A}\cdot\mathbf{B}}
{|\mathbf{A}|;|\mathbf{B}|}}
$$

Where:

* **A · B** = Dot product of vectors
* **||A||** = Magnitude (length) of vector A
* **||B||** = Magnitude (length) of vector B

---

## Output Range


$$-1 \leq \text{Cosine Similarity} \leq 1$$

| Value  | Meaning                              |
| ------ | ------------------------------------ |
| **1**  | Exactly the same direction           |
| **0**  | Completely unrelated (perpendicular) |
| **-1** | Exactly opposite directions          |



## Why is it used?

Cosine similarity is useful when **direction is more important than magnitude**.

Examples:

* Document similarity
* Search engines
* Recommendation systems
* Sentence embeddings
* NLP (Natural Language Processing)

---



In [21]:
A = np.array([2, 5, 1])

B = np.array([2, 5, 1])

print(f"Cosine Similarity = \n{cosine_similarity(A , B)}") # Same

A = np.array([1, 2])
B = np.array([-1, -2])
print(f"\nCosine Similarity = \n{cosine_similarity(A , B)}") # Opposite


A = np.array([1, 0])
B = np.array([0, 1])
print(f"\nCosine Similarity = \n{cosine_similarity(A , B)}") # Perpendicular

Cosine Similarity = 
1.0

Cosine Similarity = 
-0.9999999999999998

Cosine Similarity = 
0.0



# 2. L2 Distance (Euclidean Distance)

## Definition

**L2 Distance**, also called **Euclidean Distance**, measures the **straight-line distance** between two vectors in Euclidean space.

In simple words:

> It tells **how far apart two vectors (or points) are**.

---

## Formula


$$\boxed{
\text{L2 Distance}=\sqrt{\sum_{i=1}^{n}(A_i-B_i)^2}
}$$


Where

* ($A_i$) = ith element of vector A
* ($B_i$) = ith element of vector B

---

## Output Range


$$0 \leq \text{Distance} < \infty$$


| Value       | Meaning                  |
| ----------- | ------------------------ |
| **0**       | Exactly the same vectors |
| Small value | Very close               |
| Large value | Very different           |


## Why is it used?

L2 Distance is useful when the **actual distance between points matters**.

Examples:

* K-Nearest Neighbors (KNN)
* Clustering (K-Means)
* Image comparison
* Pattern recognition
* Robotics and computer vision



In [25]:
A = np.array([1,2,3])
B = np.array([5,4,3])

print(f"Distance : \n{l2_distance(A , B):.2f} Units")

Distance : 
4.47 Units


# **One hot Encoding**

* **One-Hot Encoding** is a technique used to convert **categorical (text) data into numerical vectors** so that machine learning models can understand and process it.

* Many machine learning algorithms cannot work directly with text labels like `"Cat"` or `"Red"`. One-hot encoding represents each category as a binary (0 and 1) vector.
---
## Why is it used?

Suppose you have the colors:

```
Red
Green
Blue
```

A machine learning model cannot perform mathematical operations on these words.

One-hot encoding converts them into numbers without implying any order.

---

## Example

Categories:

```
["Red", "Green", "Blue"]
```

Assign each category a position.

| Category | One-Hot Vector |
| -------- | -------------- |
| Red      | [1, 0, 0]      |
| Green    | [0, 1, 0]      |
| Blue     | [0, 0, 1]      |

Notice that:

* Only **one value is 1**
* All remaining values are **0**

Hence the name **One-Hot Encoding**.

---

## Another Example

Suppose the fruits are:

```
Apple
Banana
Orange
Mango
```

| Fruit  | One-Hot Vector |
| ------ | -------------- |
| Apple  | [1, 0, 0, 0]   |
| Banana | [0, 1, 0, 0]   |
| Orange | [0, 0, 1, 0]   |
| Mango  | [0, 0, 0, 1]   |

---

## Formula

For **N** categories,

Each category is represented by a vector of length **N**:


$$v_i =
\begin{cases}
1, & \text{if } i \text{ is the selected category}\
0, & \text{otherwise}
\end{cases}$$


where:

* **N** = total number of unique categories
* Exactly **one element equals 1**
* All other elements equal **0**


## Applications

One-hot encoding is commonly used for:

* Machine Learning
* Deep Learning
* Neural Networks
* Data Preprocessing
* Classification problems
* Encoding labels and categorical features




In [26]:
from one_hot_encoding import one_hot_encoding_vectorized

In [29]:
labels_array = [
    "airplane", "albatross", "ant", "apple", "armadillo", 
    "bicycle", "bird", "boat", "bus", "butterfly", 
    "car", "cat", "cheetah", "chicken", "computer", 
    "cow", "crocodile", "desktop", "dog", "dolphin", 
    "eagle", "elephant", "falcon", "ferrari", "frog", 
    "giraffe", "helicopter", "horse", "iguana", "jaguar", 
    "kangaroo", "keyboard", "laptop", "lion", "lizard", 
    "monitor", "motorcycle", "mouse", "octopus", "ostrich", 
    "penguin", "phone", "pigeon", "rabbit", "shark", 
    "smartphone", "snake", "tablet", "tiger", "zebra"
]
inputs_to_find = [
    "dog",         
    "laptop",      
    "dragon",      
    "helicopter",  
    "Car",        
    "mouse"        
]
print(f"If the vector coressponding to names has all zero , it means it is not present in the labels provided.\n")
result =  one_hot_encoding_vectorized(labels_array , inputs_to_find)

for name , vector in zip(inputs_to_find , result):
    print(f"name: {name}:")
    print(f"vector : {vector}\n")


If the vector coressponding to names has all zero , it means it is not present in the labels provided.

name: dog:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

name: laptop:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

name: dragon:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

name: helicopter:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

name: Car:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]

name: mouse:
vector : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0]

