# **Activation Functions**
**Definition:**

An **activation function** is a mathematical function applied to the output of a neuron in a neural network. It determines whether and how strongly the neuron's output is passed to the next layer, introducing **non-linearity** so that the network can learn and model complex patterns in data.

**Purpose:**

* Introduces non-linearity into the neural network.
* Helps the network learn complex relationships.
* Determines the output of each neuron.

**Common Activation Functions:**

* Sigmoid
* ReLU (Rectified Linear Unit)
* Softmax

In [8]:
import sys
import os


sys.path.append('./Phase 2/Projects/Core Vectorized Operations')




import numpy as np
from Activation_functions import sigmoid , relu , softmax


## 1. Sigmoid Function

**Definition:**

The **Sigmoid function** is an activation function that maps any real-valued input to a value between **0 and 1**, making it useful for representing probabilities in binary classification problems.

### Formula

$$
\sigma(x)=\frac{1}{1+e^{-x}}
$$

where:

* (x) = input value
* (e) = Euler's number (approximately 2.71828)

### Output Range


$$0 < \sigma(x) < 1$$



In [9]:
x = np.array([-3, -1, 0, 1, 3])
print(f"Sigmoid : \n{sigmoid(x)}")

Sigmoid : 
[0.04742587 0.26894142 0.5        0.73105858 0.95257413]


## 2. ReLU (Rectified Linear Unit)

**Definition:**

The **Rectified Linear Unit (ReLU)** is an activation function that returns the input directly if it is positive; otherwise, it returns zero. It is the most widely used activation function in the hidden layers of deep neural networks.

### Formula


$$\text{ReLU}(x)=\max(0,x)$$


### Output Range


$$0 \leq \text{ReLU}(x) < \infty$$



In [10]:
array = np.array([1,-1,2,-2,3,-3,4,-4,5,-5,6,-6])
print(f"Relative linear unit : \n{relu(array)}")

Relative linear unit : 
[1 0 2 0 3 0 4 0 5 0 6 0]



# 3. Softmax Function

**Definition:**

The **Softmax function** is an activation function that converts a vector of real-valued scores into a probability distribution, where each output lies between **0 and 1**, and the sum of all output probabilities equals **1**. It is commonly used for **multi-class classification** problems.

### Formula


$$\text{Softmax}(x_i)=
\frac{e^{x_i}}
{\sum_{j=1}^{n}e^{x_j}}
$$
where:

* ($x_i$) = score of the ($i^{th}$) class
* (n) = total number of classes

### Output Range


$$0 < P(x_i) < 1$$


and


$$\sum_{i=1}^{n}P(x_i)=1$$





In [ ]:
array = np.array([[2.0, 1.0, 0.1],   
                   [0.5, 1.5, 2.0]])

new_array = softmax(array)

print(f"Softmax : \n{new_array}")
print(f"\nsum along axis 1 : \n{np.sum(new_array ,axis=1)}")
# sum along of elements along axis 1 is equal to zero Proved!

Softmax : 
[[0.65900114 0.24243297 0.09856589]
 [0.12195165 0.33149896 0.54654939]]

sum along axis 1 : 
[1. 1.]
